name: "Meta Targeting 7"
on:
  schedule:
    - cron: '30 1,3,5,7,9,11,13,15,17,19,21,23 * * *'  # Runs every 2 hours but offset by 30 minutes

      
jobs:
  update-meta-targeting:
    name: Update Meta Targeting
    runs-on: windows-latest
    strategy:
      matrix:
        iso-code: ["AT", "BE", "BG", "CY", "CZ", "DE", "DK", "EE", "ES", "FI", 
                   "FR", "GR", "HR", "HU", "IE", "IT", "LT", "LU", "LV", "MT", 
                   "NL", "PL", "PT", "RO", "SE", "SI", "SK", "US", "MX", "NZ", 
                   "CA", "AU", "IN", "GB"]
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - name: Setup - Checkout repo
        uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          needs: |
            any::tidyverse
            any::httr
            any::remotes
            any::shiny
            any::scales
            any::treemap
            any::here
            any::jsonlite
            any::janitor
            any::quarto
            any::highcharter
            any::lubridate
            any::gt
            any::gtExtras
            any::pacman
            any::openxlsx
            any::sf
            any::xml2
            any::rvest
            any::reticulate
            any::fs
            any::countrycode
            any::progress
            any::cli
            any::digest
            any::glue
            any::vroom
            any::prettydoc
            any::DT
            any::piggyback
            any::httr2
      - name: "Script - Meta Run for ${{ matrix.iso-code }}"
        run: Rscript 'get_audiences.R' "7" "${{ matrix.iso-code }}" 
